networks:
  bsingh-net:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
    image: bsingh6636/bsingh-nginx:latest
    container_name: bsingh-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bsingh-net
    depends_on:
      - backend
      - frontend
      - getdata
      - portfolio
      - bae-portfolio
      - subsnepal-frontend
      - subsnepal-backend

  backend:
    build:
      context: https://github.com/bsingh6636/EduCors-Helper.git#main:BackEnd
    image: bsingh6636/bsingh-backend:latest
    container_name: bsingh-backend
    networks:
      - bsingh-net
    environment:
      - PORT=3000

  frontend:
    build:
      context: https://github.com/bsingh6636/EduCors-Helper.git#main:FrontEnd
    image: bsingh6636/bsingh-frontend:latest
    container_name: bsingh-frontend
    networks:
      - bsingh-net

  getdata:
    build:
      context: https://github.com/bsingh6636/EduCors-Helper.git#main:getdata
    image: bsingh6636/bsingh-getdata:latest
    container_name: bsingh-getdata
    networks:
      - bsingh-net
    environment:
      - PORT=3000

  portfolio:
    build:
      context: https://github.com/bsingh6636/myPortfolio.git#main
    image: bsingh6636/bsingh-portfolio:latest
    container_name: bsingh-portfolio
    networks:
      - bsingh-net

  bae-portfolio:
    build:
      context: git@github.com:bsingh6636/cuddly-octo-funicular.git#main
    image: bsingh6636/bsingh-bae-portfolio:latest
    container_name: bsingh-bae-portfolio
    networks:
      - bsingh-net

  subsnepal-frontend:
    build:
      context: git@github.com:bsingh6636/oasisNep.git#main:reactjs
    image: bsingh6636/bsingh-subsnepal-frontend:latest
    container_name: bsingh-subsnepal-frontend
    networks:
      - bsingh-net

  subsnepal-backend:
    build:
      context: git@github.com:bsingh6636/oasisNep.git#main:nodejs
    image: bsingh6636/bsingh-subsnepal-backend:latest
    container_name: bsingh-subsnepal-backend
    networks:
      - bsingh-net
