# This file is for production deployments. It pulls pre-built images from Docker Hub.
# It assumes you have already built and pushed the images from your local machine.

networks:
  bsingh-net:
    driver: bridge

services:
  nginx:
    image: bsingh6636/bsingh-nginx:latest
    container_name: bsingh-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bsingh-net
    depends_on:
      - backend
      - frontend
      - getdata

  backend:
    image: bsingh6636/bsingh-backend:latest
    container_name: bsingh-backend
    networks:
      - bsingh-net
    env_file:
      - .env

  frontend:
    image: bsingh6636/bsingh-frontend:latest
    container_name: bsingh-frontend
    networks:
      - bsingh-net

  getdata:
    image: bsingh6636/bsingh-getdata:latest
    container_name: bsingh-getdata
    networks:
      - bsingh-net
    env_file:
      - .env

  portfolio:
    image: bsingh6636/bsingh-portfolio:latest
    container_name: bsingh-portfolio
    networks:
      - bsingh-net
    env_file:
      - .env